fix les_strip_config_t patch
On Zig 0.16.0 and IDF v6.0.1 it is translated in idf_sys.zig as:

```Zig
pub const led_strip_config_t = opaque {
    pub const led_strip_new_rmt_device = __root.led_strip_new_rmt_device;
    pub const led_strip_new_spi_device = __root.led_strip_new_spi_device;
    pub const device = __root.led_strip_new_rmt_device;
};
```

Current regexp expects `extern struct` instead of `opaque` and it fails
to remove generated declaration so we get duplicate after applying
patch.

```sh
/home/ianic/Code/esp32/zig-esp-idf-sample/imports/idf-sys.zig:12439:11: error: duplicate struct member name 'led_strip_config_t'
pub const led_strip_config_t = opaque {
          ^~~~~~~~~~~~~~~~~~
/home/ianic/Code/esp32/zig-esp-idf-sample/imports/idf-sys.zig:29393:11: note: duplicate name here
pub const led_strip_config_t = extern struct {
          ^~~~~~~~~~~~~~~~~~
```